// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grubenlampe.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	grubenlampe.proto

It has these top-level messages:
	GenericRequest
	GenericResponse
	AddUserRequest
	AddOrgRequest
	AddASNRequest
	AddTunnelRequest
	DeleteTunnelRequest
	GetTunnelsRequest
	GetTunnelsResponse
	Tunnel
	AddIPv4AddressRequest
	AddIPv4AddressResponse
	ReleaseIPv4AddressRequest
	AddIPv6PrefixRequest
	AddIPv6PrefixResponse
	ReleaseIPv6PrefixRequest
	GetBGPStatusRequest
	GetBGPStatusResponse
	BGPStatus
	GetLogsRequest
	GetLogsResponse
	Log
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenericRequest struct {
}

func (m *GenericRequest) Reset()                    { *m = GenericRequest{} }
func (m *GenericRequest) String() string            { return proto.CompactTextString(m) }
func (*GenericRequest) ProtoMessage()               {}
func (*GenericRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GenericResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *GenericResponse) Reset()                    { *m = GenericResponse{} }
func (m *GenericResponse) String() string            { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()               {}
func (*GenericResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GenericResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GenericResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddUserRequest struct {
	Email      string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password   string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	RipeHandle string `protobuf:"bytes,3,opt,name=ripe_handle,json=ripeHandle" json:"ripe_handle,omitempty"`
}

func (m *AddUserRequest) Reset()                    { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string            { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()               {}
func (*AddUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddUserRequest) GetRipeHandle() string {
	if m != nil {
		return m.RipeHandle
	}
	return ""
}

type AddOrgRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ShortName string `protobuf:"bytes,2,opt,name=short_name,json=shortName" json:"short_name,omitempty"`
	Asn       uint32 `protobuf:"varint,3,opt,name=asn" json:"asn,omitempty"`
}

func (m *AddOrgRequest) Reset()                    { *m = AddOrgRequest{} }
func (m *AddOrgRequest) String() string            { return proto.CompactTextString(m) }
func (*AddOrgRequest) ProtoMessage()               {}
func (*AddOrgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddOrgRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddOrgRequest) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *AddOrgRequest) GetAsn() uint32 {
	if m != nil {
		return m.Asn
	}
	return 0
}

type AddASNRequest struct {
	OrgShortName string `protobuf:"bytes,1,opt,name=org_short_name,json=orgShortName" json:"org_short_name,omitempty"`
	Asn          uint32 `protobuf:"varint,2,opt,name=asn" json:"asn,omitempty"`
}

func (m *AddASNRequest) Reset()                    { *m = AddASNRequest{} }
func (m *AddASNRequest) String() string            { return proto.CompactTextString(m) }
func (*AddASNRequest) ProtoMessage()               {}
func (*AddASNRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddASNRequest) GetOrgShortName() string {
	if m != nil {
		return m.OrgShortName
	}
	return ""
}

func (m *AddASNRequest) GetAsn() uint32 {
	if m != nil {
		return m.Asn
	}
	return 0
}

type AddTunnelRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Asn     uint32 `protobuf:"varint,2,opt,name=asn" json:"asn,omitempty"`
}

func (m *AddTunnelRequest) Reset()                    { *m = AddTunnelRequest{} }
func (m *AddTunnelRequest) String() string            { return proto.CompactTextString(m) }
func (*AddTunnelRequest) ProtoMessage()               {}
func (*AddTunnelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AddTunnelRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddTunnelRequest) GetAsn() uint32 {
	if m != nil {
		return m.Asn
	}
	return 0
}

type DeleteTunnelRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *DeleteTunnelRequest) Reset()                    { *m = DeleteTunnelRequest{} }
func (m *DeleteTunnelRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteTunnelRequest) ProtoMessage()               {}
func (*DeleteTunnelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteTunnelRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetTunnelsRequest struct {
	Asn uint32 `protobuf:"varint,1,opt,name=asn" json:"asn,omitempty"`
}

func (m *GetTunnelsRequest) Reset()                    { *m = GetTunnelsRequest{} }
func (m *GetTunnelsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTunnelsRequest) ProtoMessage()               {}
func (*GetTunnelsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetTunnelsRequest) GetAsn() uint32 {
	if m != nil {
		return m.Asn
	}
	return 0
}

type GetTunnelsResponse struct {
	Tunnels []*Tunnel `protobuf:"bytes,1,rep,name=tunnels" json:"tunnels,omitempty"`
}

func (m *GetTunnelsResponse) Reset()                    { *m = GetTunnelsResponse{} }
func (m *GetTunnelsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTunnelsResponse) ProtoMessage()               {}
func (*GetTunnelsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetTunnelsResponse) GetTunnels() []*Tunnel {
	if m != nil {
		return m.Tunnels
	}
	return nil
}

type Tunnel struct {
	ProviderTunnelAddress        string `protobuf:"bytes,1,opt,name=provider_tunnel_address,json=providerTunnelAddress" json:"provider_tunnel_address,omitempty"`
	CustomerTunnelAddress        string `protobuf:"bytes,2,opt,name=customer_tunnel_address,json=customerTunnelAddress" json:"customer_tunnel_address,omitempty"`
	ProviderAsn                  uint32 `protobuf:"varint,3,opt,name=provider_asn,json=providerAsn" json:"provider_asn,omitempty"`
	CustomerAsn                  uint32 `protobuf:"varint,4,opt,name=customer_asn,json=customerAsn" json:"customer_asn,omitempty"`
	ProviderTunnelInsideAddress4 string `protobuf:"bytes,5,opt,name=provider_tunnel_inside_address4,json=providerTunnelInsideAddress4" json:"provider_tunnel_inside_address4,omitempty"`
	CustomerTunnelInsideAddress4 string `protobuf:"bytes,6,opt,name=customer_tunnel_inside_address4,json=customerTunnelInsideAddress4" json:"customer_tunnel_inside_address4,omitempty"`
	ProviderTunnelInsideAddress6 string `protobuf:"bytes,7,opt,name=provider_tunnel_inside_address6,json=providerTunnelInsideAddress6" json:"provider_tunnel_inside_address6,omitempty"`
	CustomerTunnelInsideAddress6 string `protobuf:"bytes,8,opt,name=customer_tunnel_inside_address6,json=customerTunnelInsideAddress6" json:"customer_tunnel_inside_address6,omitempty"`
	Provisioned                  bool   `protobuf:"varint,9,opt,name=provisioned" json:"provisioned,omitempty"`
}

func (m *Tunnel) Reset()                    { *m = Tunnel{} }
func (m *Tunnel) String() string            { return proto.CompactTextString(m) }
func (*Tunnel) ProtoMessage()               {}
func (*Tunnel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Tunnel) GetProviderTunnelAddress() string {
	if m != nil {
		return m.ProviderTunnelAddress
	}
	return ""
}

func (m *Tunnel) GetCustomerTunnelAddress() string {
	if m != nil {
		return m.CustomerTunnelAddress
	}
	return ""
}

func (m *Tunnel) GetProviderAsn() uint32 {
	if m != nil {
		return m.ProviderAsn
	}
	return 0
}

func (m *Tunnel) GetCustomerAsn() uint32 {
	if m != nil {
		return m.CustomerAsn
	}
	return 0
}

func (m *Tunnel) GetProviderTunnelInsideAddress4() string {
	if m != nil {
		return m.ProviderTunnelInsideAddress4
	}
	return ""
}

func (m *Tunnel) GetCustomerTunnelInsideAddress4() string {
	if m != nil {
		return m.CustomerTunnelInsideAddress4
	}
	return ""
}

func (m *Tunnel) GetProviderTunnelInsideAddress6() string {
	if m != nil {
		return m.ProviderTunnelInsideAddress6
	}
	return ""
}

func (m *Tunnel) GetCustomerTunnelInsideAddress6() string {
	if m != nil {
		return m.CustomerTunnelInsideAddress6
	}
	return ""
}

func (m *Tunnel) GetProvisioned() bool {
	if m != nil {
		return m.Provisioned
	}
	return false
}

type AddIPv4AddressRequest struct {
	OrgShortName string `protobuf:"bytes,1,opt,name=org_short_name,json=orgShortName" json:"org_short_name,omitempty"`
}

func (m *AddIPv4AddressRequest) Reset()                    { *m = AddIPv4AddressRequest{} }
func (m *AddIPv4AddressRequest) String() string            { return proto.CompactTextString(m) }
func (*AddIPv4AddressRequest) ProtoMessage()               {}
func (*AddIPv4AddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AddIPv4AddressRequest) GetOrgShortName() string {
	if m != nil {
		return m.OrgShortName
	}
	return ""
}

type AddIPv4AddressResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *AddIPv4AddressResponse) Reset()                    { *m = AddIPv4AddressResponse{} }
func (m *AddIPv4AddressResponse) String() string            { return proto.CompactTextString(m) }
func (*AddIPv4AddressResponse) ProtoMessage()               {}
func (*AddIPv4AddressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AddIPv4AddressResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddIPv4AddressResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AddIPv4AddressResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ReleaseIPv4AddressRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *ReleaseIPv4AddressRequest) Reset()                    { *m = ReleaseIPv4AddressRequest{} }
func (m *ReleaseIPv4AddressRequest) String() string            { return proto.CompactTextString(m) }
func (*ReleaseIPv4AddressRequest) ProtoMessage()               {}
func (*ReleaseIPv4AddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ReleaseIPv4AddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AddIPv6PrefixRequest struct {
	OrgShortName string `protobuf:"bytes,1,opt,name=org_short_name,json=orgShortName" json:"org_short_name,omitempty"`
}

func (m *AddIPv6PrefixRequest) Reset()                    { *m = AddIPv6PrefixRequest{} }
func (m *AddIPv6PrefixRequest) String() string            { return proto.CompactTextString(m) }
func (*AddIPv6PrefixRequest) ProtoMessage()               {}
func (*AddIPv6PrefixRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *AddIPv6PrefixRequest) GetOrgShortName() string {
	if m != nil {
		return m.OrgShortName
	}
	return ""
}

type AddIPv6PrefixResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Prefix  string `protobuf:"bytes,3,opt,name=prefix" json:"prefix,omitempty"`
}

func (m *AddIPv6PrefixResponse) Reset()                    { *m = AddIPv6PrefixResponse{} }
func (m *AddIPv6PrefixResponse) String() string            { return proto.CompactTextString(m) }
func (*AddIPv6PrefixResponse) ProtoMessage()               {}
func (*AddIPv6PrefixResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *AddIPv6PrefixResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddIPv6PrefixResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AddIPv6PrefixResponse) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

type ReleaseIPv6PrefixRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *ReleaseIPv6PrefixRequest) Reset()                    { *m = ReleaseIPv6PrefixRequest{} }
func (m *ReleaseIPv6PrefixRequest) String() string            { return proto.CompactTextString(m) }
func (*ReleaseIPv6PrefixRequest) ProtoMessage()               {}
func (*ReleaseIPv6PrefixRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ReleaseIPv6PrefixRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetBGPStatusRequest struct {
	Asn uint32 `protobuf:"varint,1,opt,name=asn" json:"asn,omitempty"`
}

func (m *GetBGPStatusRequest) Reset()                    { *m = GetBGPStatusRequest{} }
func (m *GetBGPStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBGPStatusRequest) ProtoMessage()               {}
func (*GetBGPStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetBGPStatusRequest) GetAsn() uint32 {
	if m != nil {
		return m.Asn
	}
	return 0
}

type GetBGPStatusResponse struct {
	Success   bool         `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Mesage    string       `protobuf:"bytes,2,opt,name=mesage" json:"mesage,omitempty"`
	BgpStatus []*BGPStatus `protobuf:"bytes,3,rep,name=bgp_status,json=bgpStatus" json:"bgp_status,omitempty"`
}

func (m *GetBGPStatusResponse) Reset()                    { *m = GetBGPStatusResponse{} }
func (m *GetBGPStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBGPStatusResponse) ProtoMessage()               {}
func (*GetBGPStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetBGPStatusResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetBGPStatusResponse) GetMesage() string {
	if m != nil {
		return m.Mesage
	}
	return ""
}

func (m *GetBGPStatusResponse) GetBgpStatus() []*BGPStatus {
	if m != nil {
		return m.BgpStatus
	}
	return nil
}

type BGPStatus struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Asn     uint32 `protobuf:"varint,2,opt,name=asn" json:"asn,omitempty"`
	State   uint32 `protobuf:"varint,3,opt,name=state" json:"state,omitempty"`
}

func (m *BGPStatus) Reset()                    { *m = BGPStatus{} }
func (m *BGPStatus) String() string            { return proto.CompactTextString(m) }
func (*BGPStatus) ProtoMessage()               {}
func (*BGPStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *BGPStatus) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *BGPStatus) GetAsn() uint32 {
	if m != nil {
		return m.Asn
	}
	return 0
}

func (m *BGPStatus) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type GetLogsRequest struct {
	OrgShortName string `protobuf:"bytes,1,opt,name=org_short_name,json=orgShortName" json:"org_short_name,omitempty"`
}

func (m *GetLogsRequest) Reset()                    { *m = GetLogsRequest{} }
func (m *GetLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLogsRequest) ProtoMessage()               {}
func (*GetLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *GetLogsRequest) GetOrgShortName() string {
	if m != nil {
		return m.OrgShortName
	}
	return ""
}

type GetLogsResponse struct {
	Logs []*Log `protobuf:"bytes,1,rep,name=logs" json:"logs,omitempty"`
}

func (m *GetLogsResponse) Reset()                    { *m = GetLogsResponse{} }
func (m *GetLogsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLogsResponse) ProtoMessage()               {}
func (*GetLogsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *GetLogsResponse) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Log struct {
	User         string                     `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	OrgShortName string                     `protobuf:"bytes,2,opt,name=org_short_name,json=orgShortName" json:"org_short_name,omitempty"`
	Request      string                     `protobuf:"bytes,3,opt,name=request" json:"request,omitempty"`
	Response     string                     `protobuf:"bytes,4,opt,name=response" json:"response,omitempty"`
	Time         *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=time" json:"time,omitempty"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *Log) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Log) GetOrgShortName() string {
	if m != nil {
		return m.OrgShortName
	}
	return ""
}

func (m *Log) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *Log) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *Log) GetTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*GenericRequest)(nil), "api.GenericRequest")
	proto.RegisterType((*GenericResponse)(nil), "api.GenericResponse")
	proto.RegisterType((*AddUserRequest)(nil), "api.AddUserRequest")
	proto.RegisterType((*AddOrgRequest)(nil), "api.AddOrgRequest")
	proto.RegisterType((*AddASNRequest)(nil), "api.AddASNRequest")
	proto.RegisterType((*AddTunnelRequest)(nil), "api.AddTunnelRequest")
	proto.RegisterType((*DeleteTunnelRequest)(nil), "api.DeleteTunnelRequest")
	proto.RegisterType((*GetTunnelsRequest)(nil), "api.GetTunnelsRequest")
	proto.RegisterType((*GetTunnelsResponse)(nil), "api.GetTunnelsResponse")
	proto.RegisterType((*Tunnel)(nil), "api.Tunnel")
	proto.RegisterType((*AddIPv4AddressRequest)(nil), "api.AddIPv4AddressRequest")
	proto.RegisterType((*AddIPv4AddressResponse)(nil), "api.AddIPv4AddressResponse")
	proto.RegisterType((*ReleaseIPv4AddressRequest)(nil), "api.ReleaseIPv4AddressRequest")
	proto.RegisterType((*AddIPv6PrefixRequest)(nil), "api.AddIPv6PrefixRequest")
	proto.RegisterType((*AddIPv6PrefixResponse)(nil), "api.AddIPv6PrefixResponse")
	proto.RegisterType((*ReleaseIPv6PrefixRequest)(nil), "api.ReleaseIPv6PrefixRequest")
	proto.RegisterType((*GetBGPStatusRequest)(nil), "api.GetBGPStatusRequest")
	proto.RegisterType((*GetBGPStatusResponse)(nil), "api.GetBGPStatusResponse")
	proto.RegisterType((*BGPStatus)(nil), "api.BGPStatus")
	proto.RegisterType((*GetLogsRequest)(nil), "api.GetLogsRequest")
	proto.RegisterType((*GetLogsResponse)(nil), "api.GetLogsResponse")
	proto.RegisterType((*Log)(nil), "api.Log")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Grubenlampe service

type GrubenlampeClient interface {
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	AddOrg(ctx context.Context, in *AddOrgRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	AddASN(ctx context.Context, in *AddASNRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	AddTunnel(ctx context.Context, in *AddTunnelRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	DeleteTunnel(ctx context.Context, in *DeleteTunnelRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	GetTunnels(ctx context.Context, in *GetTunnelsRequest, opts ...grpc.CallOption) (*GetTunnelsResponse, error)
	AddIPv4Address(ctx context.Context, in *AddIPv4AddressRequest, opts ...grpc.CallOption) (*AddIPv4AddressResponse, error)
	ReleaseIPv4Address(ctx context.Context, in *ReleaseIPv4AddressRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	AddIPv6Prefix(ctx context.Context, in *AddIPv6PrefixRequest, opts ...grpc.CallOption) (*AddIPv6PrefixResponse, error)
	ReleaseIPv6Prefix(ctx context.Context, in *ReleaseIPv6PrefixRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	GetBGPStatus(ctx context.Context, in *GetBGPStatusRequest, opts ...grpc.CallOption) (*GetBGPStatusResponse, error)
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error)
}

type grubenlampeClient struct {
	cc *grpc.ClientConn
}

func NewGrubenlampeClient(cc *grpc.ClientConn) GrubenlampeClient {
	return &grubenlampeClient{cc}
}

func (c *grubenlampeClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/api.Grubenlampe/AddUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grubenlampeClient) AddOrg(ctx context.Context, in *AddOrgRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/api.Grubenlampe/AddOrg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grubenlampeClient) AddASN(ctx context.Context, in *AddASNRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/api.Grubenlampe/AddASN", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grubenlampeClient) AddTunnel(ctx context.Context, in *AddTunnelRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/api.Grubenlampe/AddTunnel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grubenlampeClient) DeleteTunnel(ctx context.Context, in *DeleteTunnelRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/api.Grubenlampe/DeleteTunnel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grubenlampeClient) GetTunnels(ctx context.Context, in *GetTunnelsRequest, opts ...grpc.CallOption) (*GetTunnelsResponse, error) {
	out := new(GetTunnelsResponse)
	err := grpc.Invoke(ctx, "/api.Grubenlampe/GetTunnels", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grubenlampeClient) AddIPv4Address(ctx context.Context, in *AddIPv4AddressRequest, opts ...grpc.CallOption) (*AddIPv4AddressResponse, error) {
	out := new(AddIPv4AddressResponse)
	err := grpc.Invoke(ctx, "/api.Grubenlampe/AddIPv4Address", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grubenlampeClient) ReleaseIPv4Address(ctx context.Context, in *ReleaseIPv4AddressRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/api.Grubenlampe/ReleaseIPv4Address", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grubenlampeClient) AddIPv6Prefix(ctx context.Context, in *AddIPv6PrefixRequest, opts ...grpc.CallOption) (*AddIPv6PrefixResponse, error) {
	out := new(AddIPv6PrefixResponse)
	err := grpc.Invoke(ctx, "/api.Grubenlampe/AddIPv6Prefix", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grubenlampeClient) ReleaseIPv6Prefix(ctx context.Context, in *ReleaseIPv6PrefixRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/api.Grubenlampe/ReleaseIPv6Prefix", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grubenlampeClient) GetBGPStatus(ctx context.Context, in *GetBGPStatusRequest, opts ...grpc.CallOption) (*GetBGPStatusResponse, error) {
	out := new(GetBGPStatusResponse)
	err := grpc.Invoke(ctx, "/api.Grubenlampe/GetBGPStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grubenlampeClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error) {
	out := new(GetLogsResponse)
	err := grpc.Invoke(ctx, "/api.Grubenlampe/GetLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Grubenlampe service

type GrubenlampeServer interface {
	AddUser(context.Context, *AddUserRequest) (*GenericResponse, error)
	AddOrg(context.Context, *AddOrgRequest) (*GenericResponse, error)
	AddASN(context.Context, *AddASNRequest) (*GenericResponse, error)
	AddTunnel(context.Context, *AddTunnelRequest) (*GenericResponse, error)
	DeleteTunnel(context.Context, *DeleteTunnelRequest) (*GenericResponse, error)
	GetTunnels(context.Context, *GetTunnelsRequest) (*GetTunnelsResponse, error)
	AddIPv4Address(context.Context, *AddIPv4AddressRequest) (*AddIPv4AddressResponse, error)
	ReleaseIPv4Address(context.Context, *ReleaseIPv4AddressRequest) (*GenericResponse, error)
	AddIPv6Prefix(context.Context, *AddIPv6PrefixRequest) (*AddIPv6PrefixResponse, error)
	ReleaseIPv6Prefix(context.Context, *ReleaseIPv6PrefixRequest) (*GenericResponse, error)
	GetBGPStatus(context.Context, *GetBGPStatusRequest) (*GetBGPStatusResponse, error)
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error)
}

func RegisterGrubenlampeServer(s *grpc.Server, srv GrubenlampeServer) {
	s.RegisterService(&_Grubenlampe_serviceDesc, srv)
}

func _Grubenlampe_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrubenlampeServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grubenlampe/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrubenlampeServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grubenlampe_AddOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrubenlampeServer).AddOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grubenlampe/AddOrg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrubenlampeServer).AddOrg(ctx, req.(*AddOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grubenlampe_AddASN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddASNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrubenlampeServer).AddASN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grubenlampe/AddASN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrubenlampeServer).AddASN(ctx, req.(*AddASNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grubenlampe_AddTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrubenlampeServer).AddTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grubenlampe/AddTunnel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrubenlampeServer).AddTunnel(ctx, req.(*AddTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grubenlampe_DeleteTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrubenlampeServer).DeleteTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grubenlampe/DeleteTunnel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrubenlampeServer).DeleteTunnel(ctx, req.(*DeleteTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grubenlampe_GetTunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTunnelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrubenlampeServer).GetTunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grubenlampe/GetTunnels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrubenlampeServer).GetTunnels(ctx, req.(*GetTunnelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grubenlampe_AddIPv4Address_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIPv4AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrubenlampeServer).AddIPv4Address(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grubenlampe/AddIPv4Address",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrubenlampeServer).AddIPv4Address(ctx, req.(*AddIPv4AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grubenlampe_ReleaseIPv4Address_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseIPv4AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrubenlampeServer).ReleaseIPv4Address(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grubenlampe/ReleaseIPv4Address",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrubenlampeServer).ReleaseIPv4Address(ctx, req.(*ReleaseIPv4AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grubenlampe_AddIPv6Prefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIPv6PrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrubenlampeServer).AddIPv6Prefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grubenlampe/AddIPv6Prefix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrubenlampeServer).AddIPv6Prefix(ctx, req.(*AddIPv6PrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grubenlampe_ReleaseIPv6Prefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseIPv6PrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrubenlampeServer).ReleaseIPv6Prefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grubenlampe/ReleaseIPv6Prefix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrubenlampeServer).ReleaseIPv6Prefix(ctx, req.(*ReleaseIPv6PrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grubenlampe_GetBGPStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBGPStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrubenlampeServer).GetBGPStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grubenlampe/GetBGPStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrubenlampeServer).GetBGPStatus(ctx, req.(*GetBGPStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grubenlampe_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrubenlampeServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Grubenlampe/GetLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrubenlampeServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grubenlampe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Grubenlampe",
	HandlerType: (*GrubenlampeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _Grubenlampe_AddUser_Handler,
		},
		{
			MethodName: "AddOrg",
			Handler:    _Grubenlampe_AddOrg_Handler,
		},
		{
			MethodName: "AddASN",
			Handler:    _Grubenlampe_AddASN_Handler,
		},
		{
			MethodName: "AddTunnel",
			Handler:    _Grubenlampe_AddTunnel_Handler,
		},
		{
			MethodName: "DeleteTunnel",
			Handler:    _Grubenlampe_DeleteTunnel_Handler,
		},
		{
			MethodName: "GetTunnels",
			Handler:    _Grubenlampe_GetTunnels_Handler,
		},
		{
			MethodName: "AddIPv4Address",
			Handler:    _Grubenlampe_AddIPv4Address_Handler,
		},
		{
			MethodName: "ReleaseIPv4Address",
			Handler:    _Grubenlampe_ReleaseIPv4Address_Handler,
		},
		{
			MethodName: "AddIPv6Prefix",
			Handler:    _Grubenlampe_AddIPv6Prefix_Handler,
		},
		{
			MethodName: "ReleaseIPv6Prefix",
			Handler:    _Grubenlampe_ReleaseIPv6Prefix_Handler,
		},
		{
			MethodName: "GetBGPStatus",
			Handler:    _Grubenlampe_GetBGPStatus_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _Grubenlampe_GetLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grubenlampe.proto",
}

func init() { proto.RegisterFile("grubenlampe.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 930 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5b, 0x73, 0xdb, 0x44,
	0x14, 0xae, 0xe3, 0xd4, 0x8e, 0x8e, 0xd3, 0x90, 0x6c, 0x6e, 0x8a, 0x68, 0x49, 0xd0, 0xd0, 0x21,
	0x2f, 0x38, 0x33, 0xc1, 0xe8, 0x81, 0xbb, 0x19, 0x32, 0x6e, 0x21, 0x84, 0x8c, 0x12, 0x9e, 0x3d,
	0xb2, 0x75, 0xa2, 0x6a, 0xc6, 0xd6, 0x8a, 0x5d, 0xb9, 0xe5, 0xe7, 0xf0, 0xc2, 0xbf, 0xe4, 0x81,
	0xd9, 0x9b, 0x6e, 0x96, 0x6b, 0x02, 0x6f, 0x3a, 0xb7, 0xef, 0x9c, 0x23, 0x69, 0xbf, 0x6f, 0x61,
	0x2f, 0x62, 0x8b, 0x09, 0x26, 0xb3, 0x60, 0x9e, 0x62, 0x3f, 0x65, 0x34, 0xa3, 0xa4, 0x1d, 0xa4,
	0xb1, 0x73, 0x1a, 0x51, 0x1a, 0xcd, 0xf0, 0x42, 0xba, 0x26, 0x8b, 0x87, 0x8b, 0x2c, 0x9e, 0x23,
	0xcf, 0x82, 0x79, 0xaa, 0xb2, 0xdc, 0x5d, 0xd8, 0x19, 0x61, 0x82, 0x2c, 0x9e, 0xfa, 0xf8, 0xfb,
	0x02, 0x79, 0xe6, 0x5e, 0xc1, 0x07, 0xb9, 0x87, 0xa7, 0x34, 0xe1, 0x48, 0x6c, 0xe8, 0xf2, 0xc5,
	0x74, 0x8a, 0x9c, 0xdb, 0xad, 0xb3, 0xd6, 0xf9, 0x96, 0x6f, 0x4c, 0x11, 0x99, 0x23, 0xe7, 0x41,
	0x84, 0xf6, 0xc6, 0x59, 0xeb, 0xdc, 0xf2, 0x8d, 0xe9, 0x4e, 0x61, 0x67, 0x18, 0x86, 0xbf, 0x71,
	0x64, 0x1a, 0x98, 0x1c, 0xc0, 0x53, 0x9c, 0x07, 0xf1, 0x4c, 0x62, 0x58, 0xbe, 0x32, 0x88, 0x03,
	0x5b, 0x69, 0xc0, 0xf9, 0x3b, 0xca, 0x42, 0x0d, 0x91, 0xdb, 0xe4, 0x14, 0x7a, 0x2c, 0x4e, 0x71,
	0xfc, 0x26, 0x48, 0xc2, 0x19, 0xda, 0x6d, 0x19, 0x06, 0xe1, 0x7a, 0x25, 0x3d, 0xee, 0x3d, 0x3c,
	0x1b, 0x86, 0xe1, 0xaf, 0x2c, 0x32, 0x3d, 0x08, 0x6c, 0x26, 0xc1, 0x1c, 0x75, 0x0b, 0xf9, 0x4c,
	0x5e, 0x00, 0xf0, 0x37, 0x94, 0x65, 0x63, 0x19, 0x51, 0x3d, 0x2c, 0xe9, 0xb9, 0x11, 0xe1, 0x5d,
	0x68, 0x07, 0x3c, 0x91, 0xe0, 0xcf, 0x7c, 0xf1, 0xe8, 0x8e, 0x24, 0xea, 0xf0, 0xee, 0xc6, 0xa0,
	0x7e, 0x02, 0x3b, 0x94, 0x45, 0xe3, 0x12, 0x8a, 0xc2, 0xdf, 0xa6, 0x2c, 0xba, 0xab, 0x03, 0x6d,
	0x14, 0x40, 0xdf, 0xc2, 0xee, 0x30, 0x0c, 0xef, 0x17, 0x49, 0x82, 0x33, 0x83, 0x65, 0x43, 0x37,
	0x08, 0x43, 0x66, 0xde, 0xa5, 0xe5, 0x1b, 0xb3, 0xa1, 0xfe, 0x02, 0xf6, 0x7f, 0xc4, 0x19, 0x66,
	0xf8, 0x2f, 0x21, 0xdc, 0x97, 0xb0, 0x37, 0xc2, 0x4c, 0x65, 0x73, 0x93, 0xae, 0x71, 0x5b, 0x05,
	0xee, 0x57, 0x40, 0xca, 0x69, 0xfa, 0x2b, 0xbf, 0x84, 0x6e, 0xa6, 0x5c, 0x76, 0xeb, 0xac, 0x7d,
	0xde, 0xbb, 0xec, 0xf5, 0x83, 0x34, 0xee, 0xeb, 0xde, 0x26, 0xe6, 0xfe, 0xdd, 0x86, 0x8e, 0xf2,
	0x11, 0x0f, 0x8e, 0x53, 0x46, 0xdf, 0xc6, 0x21, 0xb2, 0xb1, 0x0a, 0x8f, 0xab, 0x83, 0x1d, 0x9a,
	0xb0, 0x2a, 0x18, 0xea, 0x4d, 0x3d, 0x38, 0x9e, 0x2e, 0x78, 0x46, 0xe7, 0xcb, 0x75, 0xea, 0xf3,
	0x1c, 0x9a, 0x70, 0xb5, 0xee, 0x63, 0xd8, 0xce, 0xfb, 0x15, 0xdf, 0xac, 0x67, 0x7c, 0x43, 0x9e,
	0x88, 0x94, 0x1c, 0x5a, 0xa4, 0x6c, 0xaa, 0x14, 0xe3, 0x13, 0x29, 0x57, 0x70, 0x5a, 0x9f, 0x3a,
	0x4e, 0x78, 0x1c, 0xa2, 0x19, 0x62, 0x60, 0x3f, 0x95, 0x53, 0x3c, 0xaf, 0x4e, 0xff, 0x5a, 0x26,
	0xe9, 0x59, 0x06, 0x02, 0xa6, 0xbe, 0x44, 0x1d, 0xa6, 0xa3, 0x60, 0xaa, 0xcb, 0x2c, 0xc3, 0xbc,
	0x7f, 0x1a, 0xcf, 0xee, 0xae, 0x9d, 0xc6, 0x5b, 0x3f, 0x8d, 0x67, 0x6f, 0xad, 0x9d, 0xc6, 0x23,
	0x67, 0xa0, 0xde, 0x26, 0x8f, 0x69, 0x82, 0xa1, 0x6d, 0xc9, 0xd3, 0x5e, 0x76, 0xb9, 0xdf, 0xc0,
	0xe1, 0x30, 0x0c, 0x5f, 0xdf, 0xbe, 0x1d, 0xe8, 0xa2, 0x47, 0x1d, 0x12, 0xf7, 0x01, 0x8e, 0xea,
	0xe5, 0xff, 0x9d, 0x64, 0xca, 0x27, 0xa1, 0x5d, 0x3d, 0x09, 0x5f, 0xc0, 0x89, 0x8f, 0x33, 0x0c,
	0x38, 0x36, 0x8c, 0xba, 0xfa, 0x00, 0x7d, 0x0d, 0x07, 0x6a, 0x3c, 0xef, 0x96, 0xe1, 0x43, 0xfc,
	0xc7, 0xe3, 0x96, 0x9b, 0x9a, 0x77, 0x93, 0x57, 0xff, 0x8f, 0xdd, 0x8e, 0xa0, 0x93, 0x4a, 0x14,
	0xbd, 0x9a, 0xb6, 0xdc, 0x01, 0xd8, 0xc5, 0x66, 0xb5, 0x31, 0x57, 0x2f, 0xf6, 0x29, 0xec, 0x8f,
	0x30, 0xfb, 0x61, 0x74, 0x7b, 0x97, 0x05, 0xd9, 0xe2, 0x3d, 0xdc, 0xf0, 0x0e, 0x0e, 0xaa, 0x89,
	0x6b, 0x57, 0x38, 0x82, 0xce, 0x1c, 0x4b, 0x1b, 0x68, 0x8b, 0x7c, 0x06, 0x30, 0x89, 0xd2, 0x31,
	0x97, 0x38, 0x76, 0x5b, 0x52, 0xca, 0x8e, 0xa4, 0x94, 0x02, 0xdd, 0x9a, 0x44, 0xa9, 0x7a, 0x74,
	0x7f, 0x01, 0x2b, 0xf7, 0x3f, 0x86, 0x25, 0x85, 0xae, 0x88, 0x1e, 0xa8, 0xe9, 0x40, 0x19, 0xae,
	0x27, 0x84, 0x2d, 0xbb, 0xa6, 0xd1, 0x23, 0x7f, 0xd0, 0x0b, 0x21, 0x7f, 0xba, 0x4e, 0xaf, 0xfe,
	0x1c, 0x36, 0x67, 0x34, 0x32, 0xac, 0xb8, 0x25, 0x57, 0xb8, 0xa6, 0x91, 0x2f, 0xbd, 0xee, 0x5f,
	0x2d, 0x68, 0x5f, 0xd3, 0x48, 0x48, 0xcf, 0x82, 0x23, 0x33, 0xd2, 0x23, 0x9e, 0x1b, 0x5a, 0x6e,
	0x34, 0x08, 0x87, 0x0d, 0x5d, 0xa6, 0x66, 0x34, 0x7f, 0xb1, 0x36, 0x85, 0x38, 0x32, 0x3d, 0x85,
	0x64, 0x32, 0xcb, 0xcf, 0x6d, 0xd2, 0x87, 0x4d, 0x21, 0xe6, 0x92, 0xab, 0x7a, 0x97, 0x4e, 0x5f,
	0x29, 0x7d, 0xdf, 0x28, 0x7d, 0xff, 0xde, 0x28, 0xbd, 0x2f, 0xf3, 0x2e, 0xff, 0xec, 0x40, 0x6f,
	0x54, 0xdc, 0x12, 0x88, 0x07, 0x5d, 0x2d, 0xd0, 0x64, 0x5f, 0xae, 0x54, 0x95, 0x6b, 0xe7, 0x40,
	0x3a, 0x6b, 0x57, 0x01, 0xf7, 0x09, 0x19, 0x40, 0x47, 0x69, 0x2e, 0x21, 0xa6, 0xac, 0x10, 0xe0,
	0x35, 0x55, 0xc3, 0xbb, 0x9b, 0xa2, 0xaa, 0x10, 0xd8, 0x95, 0x55, 0x5f, 0x82, 0x95, 0x0b, 0x28,
	0x39, 0x34, 0x85, 0x15, 0x35, 0x5c, 0x59, 0xfb, 0x3d, 0x6c, 0x97, 0xc5, 0x93, 0xd8, 0x32, 0xaf,
	0x41, 0x4f, 0x57, 0x22, 0x7c, 0x07, 0x50, 0xc8, 0x24, 0x39, 0xd2, 0x59, 0x35, 0x79, 0x75, 0x8e,
	0x97, 0xfc, 0x39, 0xc0, 0xcf, 0xf2, 0x0e, 0x54, 0x22, 0x20, 0xe2, 0x98, 0x1d, 0x96, 0x59, 0xc9,
	0xf9, 0xb0, 0x31, 0x96, 0x83, 0x5d, 0x03, 0x59, 0x66, 0x34, 0xf2, 0x91, 0x2c, 0x5a, 0x49, 0x75,
	0x2b, 0x77, 0x7b, 0x25, 0xef, 0x38, 0x05, 0x83, 0x90, 0x93, 0x52, 0xf7, 0x2a, 0xab, 0x38, 0x4e,
	0x53, 0x28, 0x47, 0xfa, 0x09, 0xf6, 0x96, 0xf8, 0x88, 0xbc, 0xa8, 0x8d, 0x55, 0x43, 0x5c, 0x35,
	0xd5, 0x15, 0x6c, 0x97, 0xc9, 0x47, 0x7f, 0xb3, 0x06, 0xe2, 0x72, 0x4e, 0x1a, 0x22, 0x39, 0x8c,
	0x07, 0x5d, 0x7d, 0x86, 0xf5, 0xaf, 0x5d, 0x65, 0x82, 0xbc, 0x7d, 0xe5, 0x98, 0xbb, 0x4f, 0x26,
	0x1d, 0x79, 0x78, 0x3e, 0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x6d, 0x91, 0x03, 0x4e, 0x0b,
	0x00, 0x00,
}
